# Generated by Django 2.2.7 on 2019-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenbankSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_ID', models.CharField(max_length=50, verbose_name='Genome ID')),
                ('accession', models.CharField(max_length=50, verbose_name='Accession')),
                ('locus_tag', models.CharField(db_index=True, max_length=50, verbose_name='locus Tag')),
                ('feature_name', models.CharField(max_length=10, verbose_name='feature name')),
                ('gene', models.CharField(blank=True, max_length=10, verbose_name='gene symbol')),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='product')),
                ('start', models.IntegerField(verbose_name='start')),
                ('end', models.IntegerField(verbose_name='end')),
                ('strand', models.IntegerField(choices=[(1, '+'), (-1, '-'), (0, '.')], verbose_name='strand')),
                ('nucl', models.CharField(blank=True, max_length=10000, verbose_name='nucl')),
                ('prot', models.CharField(blank=True, max_length=10000, verbose_name='prot')),
            ],
            options={
                'verbose_name': 'genbank summary',
                'verbose_name_plural': 'genbank data',
            },
        ),
    ]
