# Generated by Django 2.2.7 on 2019-11-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp72', '0003_genome'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='seq',
            field=models.CharField(default='', max_length=5000, verbose_name='sequence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genome',
            name='genome_ID',
            field=models.CharField(max_length=50, verbose_name='genome id'),
        ),
    ]
