# Generated by Django 2.2.7 on 2019-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp72', '0004_auto_20191112_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='end',
            field=models.IntegerField(db_index=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='genome_ID',
            field=models.CharField(db_index=True, max_length=50, verbose_name='genome id'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='start',
            field=models.IntegerField(db_index=True, verbose_name='start'),
        ),
    ]
