# Generated by Django 2.2.4 on 2019-11-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hp72.models


class Migration(migrations.Migration):

    dependencies = [
        ('hp72', '0005_auto_20191114_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genome',
        ),
    ]
