# Generated by Django 2.2.7 on 2019-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp72', '0006_manual_remove_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_ID', models.CharField(db_index=True, max_length=50, verbose_name='genome id')),
                ('start', models.IntegerField(db_index=True, verbose_name='start')),
                ('end', models.IntegerField(db_index=True, verbose_name='end')),
                ('seq', models.CharField(max_length=5000, verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'genome',
                'verbose_name_plural': 'genomes',
            },
        ),
    ]
