# Generated by Django 2.2.7 on 2019-11-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp72', '0007_genome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus_id', models.CharField(db_index=True, max_length=50, verbose_name='consensus id')),
                ('locus_tag', models.CharField(db_index=True, max_length=50, verbose_name='locus Tag')),
            ],
            options={
                'verbose_name': 'consensus group',
                'verbose_name_plural': 'consensus groups',
            },
        ),
    ]
